services:
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres_db
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    image: unihub-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres-db

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    image: unihub-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  postgres-data: